"""Regenerate the machine-readable parts of kb/ from the installed EDIABAS SGBD files.

    python tools/build_kb.py [--ecu-path C:\\EDIABAS\\Ecu]

Writes:
  kb/catalog/<SGBD>.json    jobs (args/results/comments + safety tier) and tables
  kb/catalog/README.md      index + safety classification summary
  kb/translations/pending.json  German strings that still lack an English translation
                                 (fault texts, fault types, environment names, job comments)
Curated files (kb/*.md, kb/faults/*.toml, kb/translations/de-en.json) are never touched.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from r53diag import kb, prg  # noqa: E402

# Table columns whose cells show up as result text and are worth translating.
TEXT_COLUMNS = {"ORTTEXT", "ARTTEXT", "UWTEXT", "STATUS_TEXT", "ACTION", "TEXT"}
GERMAN_HINT = re.compile(r"[äöüÄÖÜß]|\b(und|oder|nicht|der|die|das|fuer|für|bei|mit|ohne|zu|kein|ein|Fehler|"
                         r"Kurzschluss|Unterbrechung|Spannung|Leitung|Signal zu|Steuerger|Wert|Status|lesen)\b", re.I)


def sgbd_names() -> list[str]:
    names: list[str] = []
    for m in kb.modules().values():
        for s in (*m.sgbds, *( [m.group] if m.group else [])):
            if s.upper() not in names:
                names.append(s.upper())
    return names


def build(ecu_path: Path) -> None:
    out = kb.KB / "catalog"
    out.mkdir(parents=True, exist_ok=True)
    pending: dict[str, set[str]] = {}
    known = kb.translations()
    rows = []

    def want(text: str, where: str):
        t = text.strip()
        if t and t not in known and GERMAN_HINT.search(t):
            pending.setdefault(t, set()).add(where)

    for name in sgbd_names():
        path = prg.find(name, ecu_path)
        if not path:
            print(f"!! {name}: not found in {ecu_path}")
            continue
        s = prg.load(path)
        jobs = {}
        counts = {kb.READ: 0, kb.CONFIRM: 0, kb.BLOCKED: 0, "unclassified": 0}
        for jn, j in sorted(s.jobs.items()):
            tier, why = kb.classify(name, jn)
            counts["unclassified" if why.startswith("unclassified") else tier] += 1
            jobs[jn] = {
                "comment": j.comment,
                "tier": tier,
                "tier_reason": why,
                "args": [{"name": a.name, "type": a.type, "comment": a.comment} for a in j.args],
                "results": [{"name": r.name, "type": r.type, "comment": r.comment} for r in j.results],
            }
            for c in j.comment:
                want(c, f"{name}.{jn}")
        for tn, rows_ in s.tables.items():
            for row in rows_:
                for col, val in row.items():
                    if col.upper() in TEXT_COLUMNS or col.upper().endswith("TEXT"):
                        want(val, f"{name}.{tn}")
        doc = {
            "sgbd": name,
            "file": path.name,
            "kind": "group" if s.is_group else "variant",
            "header": s.header,
            "jobs": jobs,
            "tables": s.tables,
        }
        (out / f"{name}.json").write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
        rev = (s.header.get("REVISION") or [""])[0]
        comment = " ".join(s.header.get("ECUCOMMENT", []))[:90]
        rows.append((name, path.name, rev, len(jobs), counts, comment))
        print(f"{name:10} {len(jobs):4} jobs  {counts}")

    lines = [
        "# SGBD catalog (generated)",
        "",
        "Generated by `tools/build_kb.py` from the SGBD files in `C:\\EDIABAS\\Ecu`. Do not edit by hand.",
        "Each JSON file lists every job (arguments, results, BMW comments) with its safety tier from",
        "`kb/safety.toml`, plus the SGBD's lookup tables (fault texts, scaling, actuator lists).",
        "",
        "| SGBD | file | rev | jobs | read | confirm | blocked | unclassified | comment |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for name, fn, rev, n, c, comment in rows:
        lines.append(f"| {name} | {fn} | {rev} | {n} | {c['read']} | {c['confirm']} | {c['blocked']} | "
                     f"{c['unclassified']} | {comment.replace('|', '/')} |")
    lines += ["", "Unclassified jobs are blocked until reviewed and added to `kb/safety.toml`.", ""]
    (out / "README.md").write_text("\n".join(lines), encoding="utf-8")

    tdir = kb.KB / "translations"
    tdir.mkdir(exist_ok=True)
    pend = {t: sorted(w)[:3] for t, w in sorted(pending.items())}
    (tdir / "pending.json").write_text(json.dumps(pend, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"{len(pend)} strings pending translation -> kb/translations/pending.json")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--ecu-path", type=Path, default=Path(r"C:\EDIABAS\Ecu"))
    build(ap.parse_args().ecu_path)
